from django.urls import path

from .admin_views import (
    AdminExerciseListView,
    AdminExerciseRequestActionView,
    AdminExerciseRequestListView,
    AdminExerciseUpdateView,
    AdminStatsView,
    AdminUserListView,
)
from .views import (
    AddDropToGroupView,
    CategoryListView,
    ExerciseDetailView,
    ExerciseHistoryView,
    ExerciseListCreateView,
    ExerciseProgressView,
    ExerciseRequestCreateView,
    ExerciseSearchView,
    ExerciseTipsView,
    ExpandToDropsetView,
    ExpandToPairedView,
    GroupedSetCreateView,
    WorkoutSessionListCreateView,
    WorkoutSetCreateView,
    WorkoutSetDetailView,
    WorkoutTipCreateView,
)

urlpatterns = [
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('exercises/', ExerciseListCreateView.as_view(), name='exercise-list'),
    path('exercises/search/', ExerciseSearchView.as_view(), name='exercise-search'),
    path('exercises/<int:pk>/', ExerciseDetailView.as_view(), name='exercise-detail'),
    path('exercises/<int:pk>/history/', ExerciseHistoryView.as_view(), name='exercise-history'),
    path('exercises/<int:pk>/tips/', ExerciseTipsView.as_view(), name='exercise-tips'),
    path('exercises/<int:pk>/progress/', ExerciseProgressView.as_view(), name='exercise-progress'),
    path('sessions/', WorkoutSessionListCreateView.as_view(), name='session-list'),
    path(
        'sessions/<int:session_id>/sets/',
        WorkoutSetCreateView.as_view(),
        name='session-set-create',
    ),
    path(
        'sessions/<int:session_id>/grouped_sets/',
        GroupedSetCreateView.as_view(),
        name='session-grouped-set-create',
    ),
    path('sets/<int:pk>/', WorkoutSetDetailView.as_view(), name='set-detail'),
    path('sets/<int:pk>/expand_dropset/', ExpandToDropsetView.as_view(), name='set-expand-dropset'),
    path('sets/<int:pk>/expand_paired/', ExpandToPairedView.as_view(), name='set-expand-paired'),
    path('sets/<int:pk>/add_to_group/', AddDropToGroupView.as_view(), name='set-add-to-group'),
    path(
        'sessions/<int:session_id>/tips/',
        WorkoutTipCreateView.as_view(),
        name='session-tip-create',
    ),
    path('admin/stats/', AdminStatsView.as_view(), name='admin-stats'),
    path('admin/users/', AdminUserListView.as_view(), name='admin-users'),
    path('admin/exercises/', AdminExerciseListView.as_view(), name='admin-exercises'),
    path('admin/exercises/<int:pk>/', AdminExerciseUpdateView.as_view(), name='admin-exercise-update'),
    path('admin/exercise-requests/', AdminExerciseRequestListView.as_view(), name='admin-exercise-requests'),
    path('admin/exercise-requests/<int:pk>/', AdminExerciseRequestActionView.as_view(), name='admin-exercise-request-action'),
    path('exercise-requests/', ExerciseRequestCreateView.as_view(), name='exercise-request-create'),
]
