# Generated by Django 5.2.13 on 2026-04-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='set_type',
            field=models.CharField(choices=[('normal', '일반'), ('dropset', '드랍세트'), ('superset', '슈퍼세트'), ('compound', '컴파운드세트')], default='normal', max_length=10),
        ),
    ]
