# Generated by Django 5.2.13 on 2026-04-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_emailverificationcode_user_alter_workouttip_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_bodyweight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
